name: bookify
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  cupertino_icons: ^1.0.8
  lottie: ^3.3.1
  google_fonts: ^6.2.1
  curved_navigation_bar: ^1.0.6
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  google_sign_in: ^6.3.0
  image_picker: ^1.1.2
  fl_chart: ^1.0.0
  dropdown_button2: ^2.3.9
  supabase_flutter: ^2.9.1
  flutter_riverpod: ^2.3.6
  flutter_secure_storage: ^8.1.0
  country_code_picker: ^3.3.0
  animated_text_kit: ^4.2.2
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.0
  hugeicons_pro: ^0.0.1
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.1
  url_launcher: ^6.3.0
  pdf: ^3.11.0
  printing: ^5.13.0
  path_provider: ^2.1.4
  share_plus: ^10.0.2
  flutter_pdfview: ^1.4.3
  universal_html: ^2.2.4
  open_file: ^3.5.10
  permission_handler: ^11.3.1
  external_path: ^2.2.0
  flutter_slidable: ^3.1.0
  widgets_to_image: ^2.0.1
  carousel_slider: ^5.0.0
  shimmer: ^3.0.0
  flutter_zoom_drawer: ^3.1.1
  dotted_border: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
  macos:
    generate: true
    image_path: "assets/images/logo.png"
  linux:
    generate: true
    image_path: "assets/images/logo.png"
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic